GET http://localhost:3001/api/persons/1

###
DELETE  http://localhost:3001/api/persons/1

###
GET http://localhost:3001/api/persons/1

###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Jeevan",
    "number": "1234"
}